language: dart
os:
  - linux
dist: xenial
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
jobs:
  include:
    - stage: "Test"
      script: ./flutter/bin/flutter test
    - stage: "Analyze"
      script: ./flutter/bin/flutter analyze --no-current-package lib test
cache:
  directories:
    - $HOME/.pub-cache
