name: glider
description: Server-side rendering for mobile apps, powered by Flutter.
version: 0.0.2
author: Peter Bryant <peter.bryant@netsells.co.uk>
homepage: https://github.com/netsells/glider

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  cloud_firestore: any
  cloud_functions: any
  icons_helper:
    git:
      url: git://github.com/sjmcdowall/icons_helper

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
